### ISSUE TITLE
Créer UG

### ISSUE THREAD

**Issue by AurelienHAAZ** [pobsteta/gf#4]
xmla mettre à jour de gf

**Comment by AurelienHAAZ** [comment]
je ne retrouve pas ou les UG sont générées

**Comment by pobsteta** [comment]
Dans le menu action du menu Unité de gestion

**Comment by AurelienHAAZ** [comment]
Lorsqu'il n'y a pas d'UG, le menu est gris

**Comment by pobsteta** [comment]
il faut qu'il y ai au moins une ug. Crée une ug test que tu effaceras 
après la première création réalisée.
@+

**Comment by AurelienHAAZ** [comment]
c'est ce que j'ai fait mais quand j'ai cliqué sur le peuplement, un bug m'a bloqué l'ordi !
