### ISSUE TITLE
Connection serveur impossible

### ISSUE THREAD

**Issue by AurelienHAAZ** [pobsteta/gf#6]
Je n'arrive pas à me connecteur sur Tryton

**Comment by pobsteta** [comment]
L'adresse IP a changée, désolé !

![connection](https://cloud.githubusercontent.com/assets/932599/15817005/13eee3bc-2bd6-11e6-8c98-50dc8d56c2e0.png)

**Comment by pobsteta** [comment]
Bonjour,

L'adresse IP a changé, désolé ! Tu trouveras en pièce jointe le fichier 
projet QGIS pour les peuplements avec votre typologie. Il y a un exemple 
avec la forêt ELS KIECHATS.
@+

**Comment by AurelienHAAZ** [comment]
je ne trouve pas le fichier QGIS joint.

**Comment by pobsteta** [comment]
renvoyé par mail
